const STORAGE_KEY='shepherding-journal-v2';
const activities=[
['A visit to the member’s house, school, or workplace during the week.',''],['A significant interaction you had with the member OUTSIDE the church during the week','>30min'],['Counseling','on specific topics'],['Any teaching from the scriptures','includes teaching Converts'],['Prayer Time With Member','In-person'],['Prayer For Member in the shepherd’s personal ‘Making Mention’ prayer time.','Minimum of 5 mins per person'],['Eat-in: An opportunity to share a meal or a drink with the member at home.','All visits to members of the opposite sex must be in the company of others [with disciples].'],['Eat-out: An opportunity to take the member out to eat (e.g. at a KFC, buy waakye, Kenkey and fish, etc.)','All visits to members of the opposite sex must be in the company of others [with disciples].'],['Member’s social event you’ve attended','e.g. birthday visit, funeral of a loved one, outdooring of a baby, hospital visit'],['Telepastoring','Prayer and counselling over the phone']];
const weeklySections=[['PRAYER',[['Daily 3-hour prayer','check'],['Weekly long prayer','text','minimum of 9hrs'],['Saturday 3-hour prayer','check']]],['THE WORD',[['Daily quiet time','check'],['Scripture memorisation','check'],['Read in house books','check'],['Teaching and preaching','text','the word of salvation and equipping programmes (e.g. discipleship meeting, new believers school, satellite church meeting, prayer meeting, church service, RCM/COG)']]],['SOUL WINNING ACTIVITY',[['Led weekly ACOM/FTC','check'],['Number of ACMs that did outreach','number'],['Number of souls won','number'],['Number of New Souls brought to church','number'],['Visited New Converts','check'],['Visited Old Members','check'],['Visited Backslidden souls','check'],['Did Deep Sea Fishing','check'],['Counselled members','check'],['Sunday Attendance','number']]]];
const monthlySections=[['PRAYER',[['Monthly personal retreat','text','at least one day'],['Involvement in congregational prayer','check']]],['SOAKING IN THE WORD',[['Harmonised message','text','At least one complete message a month'],['Soaking in videos','text','At least one video a month']]],['GOOD ADMINISTRATION',[['Has membership database','check'],['New converts database','check'],['Database for all shepherds','check']]],['TRAINING OF SHEPHERDS',[['Has 12 apostles','check'],['Has 3 inner apostles','check'],['Has a training program','check'],['Grooms out new shepherds and potential shepherds','check']]],['LOYALTY',[['Loyalty Traits score','number'],['Faithful giver','check'],['Financial commitment','check'],['No moral issues','check']]]];
const blank={activeWeek:1,activeMonth:'',shepherding:{},weekly:{},monthly:{}};let state=load();let saveTimer;
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return x?{...structuredClone(blank),...x}:structuredClone(blank)}catch{return structuredClone(blank)}}
function save(){clearTimeout(saveTimer);setSave('Saving…');saveTimer=setTimeout(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));setSave('Saved')}catch{setSave('Storage full')}updateDashboard()},100)}
function setSave(x){const e=document.getElementById('saveText');if(e)e.textContent=x}function toast(x){const e=document.getElementById('toast');e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function wk(){return String(state.activeWeek)}function shep(){let k=wk();return state.shepherding[k]??= {month:state.activeMonth,week:state.activeWeek,prayer:Array(12).fill(false),prayerNotes:Array(12).fill(''),activities:Array(10).fill(false),comments:Array(10).fill(''),attendance:Array.from({length:4},()=>({name:'',attended:false}))}}
function weekly(){let k=wk();return state.weekly[k]??={month:state.activeMonth,week:state.activeWeek,values:{}}}function monthly(){let k=state.activeMonth||'default';return state.monthly[k]??={month:state.activeMonth,values:{}}}
function nav(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.tabbar button').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));scrollTo({top:0,behavior:'smooth'});if(v==='dashboard')updateDashboard()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b){e.preventDefault();nav(b.dataset.nav)}});
function renderShep(){let s=shep();shepMonth.value=s.month||'';shepWeek.value=state.activeWeek;let p=document.getElementById('prayerRows');p.innerHTML='';s.prayer.forEach((done,i)=>{let r=document.createElement('div');r.className='prayer-row';r.innerHTML=`<input class="check" type="checkbox" ${done?'checked':''}><label>HOUR NO. ${String(i+1).padStart(2,'0')}</label><input class="comment-input" value="${esc(s.prayerNotes[i])}" placeholder="Comment">`;let c=r.querySelector('.check'),n=r.querySelector('.comment-input');c.onchange=()=>{s.prayer[i]=c.checked;save();renderProgress()};n.oninput=()=>{s.prayerNotes[i]=n.value;save()};p.appendChild(r)});
let a=document.getElementById('activityList');a.innerHTML='';activities.forEach((x,i)=>{let r=document.createElement('div');r.className='activity-item'+(s.activities[i]?' done':'');r.innerHTML=`<div class="activity-main"><input class="check" type="checkbox" ${s.activities[i]?'checked':''}><span class="activity-num">${String(i+1).padStart(2,'0')}</span><div class="activity-title">${esc(x[0])}<small>${esc(x[1])}</small></div></div><div class="activity-comment"><input class="comment-input" value="${esc(s.comments[i])}" placeholder="COMMENTS"></div>`;let c=r.querySelector('.check'),n=r.querySelector('.comment-input');c.onchange=()=>{s.activities[i]=c.checked;r.classList.toggle('done',c.checked);save();renderProgress()};n.oninput=()=>{s.comments[i]=n.value;save()};a.appendChild(r)});
let at=document.getElementById('attendanceList');at.innerHTML='';s.attendance.forEach((x,i)=>{let r=document.createElement('div');r.className='attendance-row';r.innerHTML=`<span class="attendance-num">${i+1}</span><input class="comment-input" value="${esc(x.name)}" placeholder="NAME OF SERVICE OR MEETING"><label class="attendance-check"><input class="check" type="checkbox" ${x.attended?'checked':''}> Attended</label>`;let n=r.querySelector('.comment-input'),c=r.querySelector('.check');n.oninput=()=>{x.name=n.value;save()};c.onchange=()=>{x.attended=c.checked;save()};at.appendChild(r)});renderProgress()}
function renderProgress(){let s=shep(),p=s.prayer.filter(Boolean).length,a=s.activities.filter(Boolean).length;prayerProgress.textContent=`${p}/12`;activityProgress.textContent=`${a}/10`;dashPrayer.textContent=`${p}/12`;dashProgress.textContent=`${a}/10`;heroWeek.textContent=String(state.activeWeek).padStart(2,'0');prayerBar.style.width=p/12*100+'%';activityBar.style.width=a/10*100+'%';homeMonth.textContent=s.month||state.activeMonth||'Not set'}
function renderReport(root,data,sections){root.innerHTML='';sections.forEach((sec,si)=>{let card=document.createElement('div');card.className='report-section';card.innerHTML=`<div class="report-title">${esc(sec[0])}</div><div class="report-items"></div>`;let list=card.querySelector('.report-items');sec[1].forEach((it,ii)=>{let key=si+'-'+ii,val=data.values[key]??'';let row=document.createElement('div');row.className='report-row';let ctl=it[1]==='check'?`<div class="report-check-wrap"><label><input class="check" type="checkbox" ${val===true?'checked':''}> Done</label></div>`:`<input class="report-input" type="${it[1]==='number'?'number':'text'}" value="${esc(val)}" placeholder="${esc(it[2]||'')}">`;row.innerHTML=`<div class="report-label">${esc(it[0])}${it[2]&&it[1]==='check'?`<small>${esc(it[2])}</small>`:''}</div>${ctl}`;let input=row.querySelector('input');input.onchange=()=>{data.values[key]=it[1]==='check'?input.checked:input.value;save()};input.oninput=()=>{if(it[1]!=='check'){data.values[key]=input.value;save()}};list.appendChild(row)});root.appendChild(card)})}
function renderWeekly(){let w=weekly();weeklyMonth.value=w.month||'';weeklyWeek.value=state.activeWeek;renderReport(weeklyForm,w,weeklySections)}function renderMonthly(){let m=monthly();monthlyMonth.value=m.month||'';renderReport(monthlyForm,m,monthlySections)}
function updateDashboard(){renderProgress()}
function all(){shep();weekly();monthly();renderShep();renderWeekly();renderMonthly();renderProgress()}
shepMonth.oninput=()=>{shep().month=shepMonth.value;state.activeMonth=shepMonth.value;save()};weeklyMonth.oninput=()=>{weekly().month=weeklyMonth.value;state.activeMonth=weeklyMonth.value;save()};monthlyMonth.oninput=()=>{monthly().month=monthlyMonth.value;state.activeMonth=monthlyMonth.value;save()};shepWeek.onchange=e=>{state.activeWeek=+e.target.value;all()};weeklyWeek.onchange=e=>{state.activeWeek=+e.target.value;all()};
exportBtn.onclick=()=>{let b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='shepherding-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(u);toast('Backup exported')};importInput.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.shepherding||!x.weekly||!x.monthly)throw 0;state={...structuredClone(blank),...x};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));all();toast('Backup restored')}catch{toast('Backup could not be imported')}};r.readAsText(f);e.target.value=''};clearBtn.onclick=()=>{if(confirm('Clear all saved Shepherding Journal entries from this device?')){localStorage.removeItem(STORAGE_KEY);state=structuredClone(blank);all();toast('Entries cleared')}};
all();if('serviceWorker'in navigator&&location.protocol!=='file:')addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
